import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const familjenGrotesk = Familjen_Grotesk({
  variable: "--font-familjen-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  adjustFontFallback: true,
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${familjenGrotesk.className} h-full antialiased`}
    >
      <body className="max-w-[1400px] mx-auto relative overflow-hidden">
        <div className="-z-10 fixed top-[-10%] left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-purple-50/50 rounded-full blur-[120px] pointer-events-none" />
        <div className="-z-10 fixed top-[20%] left-[-10%] w-[500px] h-[500px] bg-red-50/50 rounded-full blur-[100px] pointer-events-none" />
        <div className="-z-10 fixed top-[20%] right-[-10%] w-[500px] h-[500px] bg-red-50/50 rounded-full blur-[100px] pointer-events-none" />

        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
